# Generated by Django 5.0.2 on 2024-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('scheduled', 'Scheduled'), ('leftover', 'Leftover'), ('finished', 'Finished')], max_length=250)),
                ('recipe', models.CharField(max_length=255)),
            ],
        ),
    ]
