# Generated by Django 5.0.2 on 2024-03-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('scheduled', 'Scheduled'), ('finished', 'Finished')], max_length=250)),
                ('dishes', models.ManyToManyField(related_name='dishes', to='meal_plan.dish')),
            ],
        ),
    ]
