# Generated by Django 5.0.2 on 2024-03-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0002_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
    ]
