# Generated by Django 5.0.2 on 2024-03-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0003_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(related_name='meals', to='meal_plan.dish'),
        ),
    ]
