# Generated by Django 5.0.2 on 2024-03-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0004_alter_dish_recipe_alter_meal_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='meals', to='meal_plan.dish'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('scheduled', 'Scheduled'), ('leftover', 'Leftover'), ('finished', 'Finished')], max_length=250),
        ),
    ]
