# Generated by Django 5.0.2 on 2024-03-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0006_grocery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('cleaner', 'Cleaning Item'), ('household', 'Household Item')], default='food', max_length=250),
        ),
    ]
