# Generated by Django 5.0.2 on 2024-03-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0007_alter_grocery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='status',
            field=models.CharField(choices=[('needed', 'Needed'), ('purchased', 'Purchased')], default='needed', max_length=250),
        ),
    ]
