# Generated by Django 5.0.2 on 2024-03-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0009_alter_grocery_dishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'verbose_name_plural': 'groceries'},
        ),
    ]
