# Generated by Django 5.0.2 on 2024-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0010_alter_grocery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='meal_plan.grocery'),
        ),
    ]
