# Generated by Django 5.0.2 on 2024-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0011_remove_grocery_dishes_dish_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='meal_plan.grocery'),
        ),
    ]
